---
title: "Introduction générale de la formation R"
format: html
editor: visual
---

<br><br>

Bienvenue sur mon petit site dédié à la formation sur R à l'ISEE !

Evidemment, il existe des centaines de sites pour se former à l'usage de R, dont beaucoup sont surement mieux construits que le mien. En revanche, ce que n'ont pas ces sites, c'est la capacité à s'adapter à vous, statisticiens de l'ISEE. Ici, j'essaierai de couvrir la formation de base, puis je rajouterai du contenu en fonction de vos demandes. Nous utiliserons même les données du recensement comme jeu de données pour les exemples, afin que ça vous parle :)

Au cours de cette formation, nous plongerons donc dans les bases de R, en commençant par la compréhension de l'environnement de travail R Studio, puis jusqu'à la manipulation de données, la création de graphiques et l'exécution d'analyses statistiques plus poussées.

<br><br>

```{r, echo = F, warning=F, message=FALSE}
# Installer et charger la bibliothèque ggplot2 (si vous ne l'avez pas déjà)
# install.packages("ggplot2")
library(ggplot2)

# Créer un jeu de données fictif
set.seed(123)
participants <- 1:100
progression_en_r <- participants * 2 + rnorm(50, mean = 0, sd = 10)
suivi_formation <- participants * 2 + rnorm(50, mean = 0, sd = 10)

data <- data.frame(Participants = participants,
                   Progression_en_R = progression_en_r,
                   Suivi_Formation = suivi_formation)

# Créer un graphique humoristique avec ggplot2 en limitant les axes à 100
ggplot(data, aes(x = Suivi_Formation, y = Progression_en_R)) +
  geom_point(size = 1, color = "#000000") +
  geom_smooth(method = "lm", color = "#EA3131", se = FALSE) +
  labs(title = "Corrélation entre suivi de formation et progression en R",
       x = "% de suivi des formations sur ce super site",
       y = "% de progression en R") +
  theme_minimal() +
  annotate("text", x = 20, y = 80, label = "Progression garantie ! ;)", color = "#000000", size = 5) +
  coord_cartesian(xlim = c(0, 100), ylim = c(0, 100))

```

<br><br><br>

Noé Barthelemy - Référent R à l'ISEE (2023-2024)
